### ISSUE TITLE
Build details page: multi-line script don't render properly

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#146]
We have this code in our YAML:

```yaml
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
      #
      # Cancel building pull requests when there aren't changed in the docs directory.
      #
      # If there are no changes (git diff exits with 0) we force the command to return with 183.
      # This is a special exit code on Read the Docs that will cancel the build immediately.
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yml requirements/docs.txt;
        then
          echo "No changes to docs/ - exiting the build.";
          exit 183;
        fi
```

After merging https://github.com/readthedocs/readthedocs.org/pull/10119 it will render as a multi-line:

![Screenshot_2023-03-07_16-56-16](https://user-images.githubusercontent.com/244656/223476335-2ebbe9e9-80d4-4361-aea3-6816126d783e.png)

However, in the new templates, it's shown as a one-line:

![Screenshot_2023-03-07_16-58-32](https://user-images.githubusercontent.com/244656/223476866-7618cdf2-839d-405a-b2c3-89d1ac3a5ba6.png)
