### ISSUE TITLE
Announcements: icon doesn't show a pointer

### ISSUE THREAD

**Issue by humitos** [readthedocs/ext-theme#534]
The `X` icon doesn't show a pointer as the notification does. @agjohnson do you know why is this? 🤔 

![Peek 2024-12-03 17-53](https://github.com/user-attachments/assets/f24ae5c9-1170-4aa1-8e36-9599baccdd82)

**Comment by agjohnson** [comment]
The close icon is not a standard part of cards, but it is in messages. The icon link on the announcement cards needs `cursor: pointer`.

**Comment by humitos** [comment]
Should we add a specific class to each of the announcements in https://github.com/readthedocs/ext-theme/tree/5879122c13ecaea42a6a2c8cd9320d2f05bf7d7f/readthedocsext/theme/templates/projects/partials/announcements and then add a CSS rule for it? Like:

```css
.announcement div.content > i {
  cursor: pointer;
}
```

**Comment by agjohnson** [comment]
I always try to work within FUI with classes when we need to customize, so that there are as few of our own custom element/classes outside what FUI provides.

So, for this I would add a rule in the `cards.overrides` file (this may not exist yet) for something more specific:

```css
.ui.card > div.content:first-child > i.close {
  cursor: pointer;
}
```

Just an example, that's probably wrong.
